version: "3"
services:
        php:
                image: php:8.1-apache
                ports:
                        - 80:80
                volumes:
                        - .:/var/www/html

        db:
                image: mysql
                volumes:
                        - ./basedata:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example









