version: "3"
services:
        php:
                build: ./website
                ports:
                        - 80:80
                volumes:
                        - ./website:/var/www/html




        event-handler:

                build: ./event-handler

                volumes:
                        - ./event-handler:/root/event_handler

                ports:
                        - 5000:5000





        db:
                image: mysql
                volumes:
                        - ./basedata:/var/lib/mysql

                restart: always


                environment:

                        MYSQL_ROOT_PASSWORD: example









