version: "3"
services:
        php:
                build: ./
                ports:
                        - 80:80
                volumes:
                        - .:/var/www/html






        db:
                image: mysql
                volumes:
                        - ./basedata:/var/lib/mysql
                ports:
                        - 3306:3306
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example









