version: "3"
services:
        php:
                build: ./
                ports:
                        - 80:80
                volumes:
                        - .:/var/www/html



        event-handler:

                build: ./event-handler
                volumes:
                        - ./event-handler:/event-handler
                ports:
                        - 5000:5000



        db:
                image: mysql
                volumes:
                        - ./basedata:/var/lib/mysql

                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example









