version: "3"
services:
        php:
                image: php:8.1-apache
                ports:
                        - 80:80

        db:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example









